name: reminder
description: reminder app
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.16.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  get: ^4.6.1
  get_storage: ^2.0.3
  freezed: ^1.1.1
  json_annotation: ^4.4.0
  dio: ^4.0.6
  flutter_otp_text_field: ^1.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
  build_runner: ^2.1.10
  freezed_annotation: ^1.1.0
  json_serializable: ^6.1.6

flutter:
  uses-material-design: true

  fonts:
    - family: Dana
      fonts:
        - asset: assets/fonts/Dana.ttf